const AA = [
  ["Glycine", "Gly", "G", "H"],
  ["Alanine", "Ala", "A", "CH3"],
  ["Valine", "Val", "V", "CH(CH3)2"],
  ["Leucine", "Leu", "L", "CH2-CH(CH3)2"],
  ["Isoleucine", "Ile", "I", "CH(CH3)-CH2-CH3"],
  ["Methionine", "Met", "M", "CH2-CH2-S-CH3"],
  ["Proline", "Pro", "P", "(CH2)3 loops back to backbone N (N has one H)"],
  ["Phenylalanine", "Phe", "F", "CH2-phenyl (benzene ring)"],
  ["Tyrosine", "Tyr", "Y", "CH2-phenyl-OH (OH opposite CH2: para)"],
  [
    "Tryptophan",
    "Trp",
    "W",
    "CH2-(1H-indol-3-yl): fused 5/6 rings, NH in 5-ring",
  ],
  ["Serine", "Ser", "S", "CH2-OH"],
  ["Threonine", "Thr", "T", "CH(OH)-CH3"],
  ["Cysteine", "Cys", "C", "CH2-SH"],
  ["Asparagine", "Asn", "N", "CH2-C(=O)-NH2"],
  ["Glutamine", "Gln", "Q", "CH2-CH2-C(=O)-NH2"],
  ["Aspartic acid", "Asp", "D", "CH2-C(=O)-OH"],
  ["Glutamic acid", "Glu", "E", "CH2-CH2-C(=O)-OH"],
  ["Lysine", "Lys", "K", "(CH2)4-NH2"],
  ["Arginine", "Arg", "R", "(CH2)3-NH-C(=NH)-NH2"],
  [
    "Histidine",
    "His",
    "H",
    "CH2-(1H-imidazol-4-yl): 5-ring, N at positions 1,3",
  ],
];
